name: transaction_app
description: A Flutter app for transaction management.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  http: ^1.1.0
  flutter_spinkit: ^5.2.0
  fl_chart: ^0.63.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/transactions.json
    - assets/N.png